- app/(services)/aiService.tsx
- app/ai/page.tsx
- app/global.css
- app/level/[id]/(components)/InputDisplay.tsx
- app/level/[id]/(models)/Score.interface.tsx
- app/level/[id]/page.tsx
- app/main.css
- app/result/page.tsx
- app/rule/page.tsx
- app/utilities.tsx
- tailwind.config.js
1. Highlights are now shown in the result page.
2. Screenshot for result is now properly formatted.
3. Countdown timer in game to let you prepare, while AI generates the taboo words associated with the target word.
4. Taboo words generated have more variations instead of just the lemma form of the guess word.
5. Minor UI updates.
6. Clear button for user input so you can quickly clear your input to write new prompt.
7. Input placeholder changes based on the status of the game, giving user more information.
> Feature Updates!

- app/(components)/DevToggle.tsx
- app/level/page.tsx
Also updated label to make it more meaningful in-game
> Bugfix: timer resume if no edit submit again

- app/(components)/(FeaturePopup)/FeaturePopup.tsx
- app/(components)/ConfirmPopUp.tsx
- app/daily-challenge/loading/page.tsx
- app/daily-challenge/page.tsx
- app/dev/daily/page.tsx
- app/layout.tsx
- app/levels/page.tsx
- app/result/page.tsx
- app/rule/page.tsx
- app/signup/page.tsx
- app/utilities.tsx
- app/whatsnew/page.tsx
- lib/cache.ts
- lib/hash.ts
- lib/services/frontend/aiService.ts
- lib/services/frontend/gameService.ts
- pages/api/users/[nickname]/getUser.ts
- pages/api/users/create.ts
- public/features/content.md
- supabase/migrations/20230327160256_create_topic_column_for_daily_challenge.sql
- types/dailyLevel.interface.ts
- types/level.interface.ts
- Backend nickname verification check
- Daily challenge with "Topic"
- `getUser` should not return `recoveryKey` in plain text
- Rule page `open ai model` link not styled 
- show confirm alert when press next on recovery key saving screen
- simplify discord button on whatsnew and feature popup
- `/level` search bar should be below loading page
- in dev mode, daily level creation should allow to switch date, existing level should not be overwritten
- in dev mode, daily level creation -> some existing words button not coloured green
- Result page total score floating point error
> Various Bug Fixes

- __test__/api/level.test.tsx
- app/add-level/layout.tsx
- app/add-level/loading.tsx
- app/add-level/page.tsx
- app/levels/layout.tsx
- app/levels/page.tsx
- app/main.css
- app/page.tsx
- components/ContactMe.tsx
- components/Header.tsx
- components/InfoButton.tsx
- lib/database/levelRespository.ts
- lib/services/backend/levelService.ts
- lib/services/frontend/emailService.ts
- lib/services/frontend/levelService.ts
- pages/api/levels/create.ts
- pages/api/levels/get.ts
- pages/api/send-email.ts
- supabase/migrations/20230729162444_add_new_column_for_level_is_verified.sql
- types/level.interface.ts
- Brand new page
- Mobile and PC friendly
- Detailed logics for not conflicting with existing taboo words
- Deep integration with Chakra UI
- Able to appeal to submit taboo words to overwrite existing
- Email API
- New column "isverified" for submitted level. Dev side can use this flag to approve or reject
- Topics /levels use "isverified" to display only verified topics
> Feature: User can submit custom topic for approval

- app/add-level/page.tsx
- app/levels/page.tsx
- app/page.tsx
- app/x/review-words/page.tsx
- components/auth-provider.tsx
- components/custom/contact-me.tsx
- components/custom/level-card.tsx
- components/custom/maintenance.tsx
- components/custom/user-login-portal.tsx
- components/header/Header.tsx
- lib/hooks/useFirebaseAuth.tsx
- lib/services/aiService.ts
- lib/services/authService.ts
- lib/services/levelService.ts
- lib/services/userService.ts
- lib/services/wordService.ts
- lib/types/level.interface.ts
- lib/types/user.interface.ts
- lib/types/word.interface.ts
- lib/utils/dateUtils.ts
- lib/utils/levelUtils.ts
- Add upcoming UI under construction
- User auth hook with user creation/update in firestore
- Update firebase security rules
- Auto save nickname when user submit a topic contribution
- Topics page add advanced sorting methods
- Fix some UI issues
- Add popularity as a Level attribute, user can sort base on that!
- Update firebase security rules to be more secure + when add new level and target words, pass in creator's emails as a token for firebase security rules to check against
> V3.0.0: Various features and bugfix

- lib/services/aiService.ts
> feat(ai): improve ai answer in game(#143)

- .prettierignore
- app/add-level/layout.tsx
- app/ai/layout.tsx
- app/buymecoffee/layout.tsx
- app/error.tsx
- app/level/[id]/layout.tsx
- app/page.tsx
- app/pwa/layout.tsx
- app/result/layout.tsx
- app/result/page.tsx
- app/roadmap/layout.tsx
- app/robots.txt
- app/rule/layout.tsx
- app/sitemap.ts
- app/sitemap/layout.tsx
- app/sitemap/loading.tsx
- app/sitemap/page.tsx
- app/whatsnew/layout.tsx
- app/x/review-words/layout.tsx
- components/analytics-wrapper.tsx
- components/custom/contact-me.tsx
- components/custom/side-menu.tsx
- lib/hooks/useAppStats.ts
- lib/metadata.ts
- lib/services/appService.ts
- lib/utils/routeUtils.ts
- next.config.js
- tailwind.config.js
- fix #177 
- fix SEO issue (no interlink)
- add aibrb feature badge
- add sitemap page
- add view counter
> 177 bug result page prompt login to submit topic will redirect to add level page

- app/roadmap/roadmap.md
- app/sitemap.ts
- app/sitemap/page.tsx
- lib/utilities.ts
- lib/utils/routeUtils.ts
- next.config.js
- package-lock.json
- package.json
- pages/api/sitemap.ts
> feat: dynamic sitemap endpoint

- app/result/page.tsx
- app/roadmap/roadmap.md
- app/sitemap.ts
- app/sitemap/page.tsx
- lib/utilities.ts
- lib/utils/routeUtils.ts
- next.config.js
- package-lock.json
- package.json
- pages/api/sitemap.ts
> v3.0.7: dynamic sitemap endpoint

- README.md
- app/page.tsx
- app/roadmap/roadmap.md
- app/sitemap/page.tsx
- components/custom/side-menu.tsx
> feat: add github link

- app/level/[id]/page.tsx
- public/manifest.json
- Fix the issue where level is loaded more than once hence variations of different target word is fetched more than once
> fix: level load multiple times, update pwa manifest

- __test__/api/x/send-email.test.ts
- app/x/review-words/page.tsx
- lib/services/emailService.ts
- pages/api/x/send-email.ts
> feat: dev mode more info and verify can resent email

- app/result/page.tsx
- app/roadmap/roadmap.md
- components/custom/share-score-dialog.tsx
- components/custom/star-rating-bar.tsx
- package-lock.json
- package.json
> Feature: 157 feat make scores meaningful

- app/layout.tsx
- app/levels/page.tsx
- app/page.tsx
- app/pwa/page.tsx
- app/result/page.tsx
- app/roadmap/roadmap.md
- components/custom/contact-me.tsx
- components/custom/home/contact-me.tsx
- components/custom/home/home-menu-button-array.tsx
- components/custom/home/home-social-link-button-array.tsx
- components/custom/home/page-counter.tsx
- components/custom/levels/levels-search-bar.tsx
- components/custom/results/results-contribution-alert-dialog.tsx
- components/custom/results/results-share-alert-dialog.tsx
- components/custom/results/results-summary-card.tsx
- components/custom/theme-toggle.tsx
- components/header/header-left-elements.tsx
- lib/utilities.ts
- lib/utils/routeUtils.ts
- next.config.js
- package-lock.json
- package.json
- bug fixes
- update theme toggle icon for follow system setting
- some component refactoring
> v3.0.11: Patch & Refactoring

- app/level/[id]/layout.tsx
- app/level/[id]/page.tsx
- app/result/page.tsx
- components/custom/level-card.tsx
- components/custom/results/results-summary-card.tsx
- lib/redux/features/scoreStorageSlice.ts
- lib/services/levelService.ts
- lib/utilities.ts
> v3.0.12: result page ai judge error with re-score

- app/level/[id]/page.tsx
- app/profile/page.tsx
- components/custom/user-login-portal.tsx
Some fixed by commit 60ca7c48d879130c05436c3e3aa5a7b4718d4747
- Fix AI mode not working
- Fix AI mode also gets uploaded to DB with records, causing displaying "UNKNOWN" in the past game results
- Add notice in profile explaining custom AI game will not be included
- Fix IconButton `asChild` issue causing UI misplaced
- Fix user login portal showing "Last Result" link even though user has logged in (missing dependency for memo)
> v3.1.0 HOTFIX: AI mode not working, AI mode uploaded to DB

- app/level/[id]/page.tsx
- app/result/page.tsx
- components/custom/home/home-menu-button-array.tsx
- components/custom/results/results-contribution-alert-dialog.tsx
- components/custom/side-menu.tsx
- components/custom/user-login-portal.tsx
- lib/event-manager.ts
- lib/persistence/persistence.ts
- middleware/rateLimit+middleware.ts
> Fix: result cache not retained after play level again but not finished. 

- app/profile/page.tsx
- components/custom/profile/profile-recent-games-scroll-view.tsx
- components/custom/profile/profile-topic-scroll-view.tsx
- components/custom/profile/topics/profile-topics-card-view.tsx
- lib/services/levelService.ts
- lib/types/userLevel.type.ts
> feat: add played topic section for user profile

- app/profile/page.tsx
- app/roadmap/roadmap.md
- components/custom/profile/profile-recent-games-scroll-view.tsx
- components/custom/profile/profile-topic-scroll-view.tsx
- components/custom/profile/topics/profile-topics-card-view.tsx
- firebase/firebase-client.ts
- lib/admin-manager.ts
- lib/hooks/useAppStats.ts
- lib/hooks/useFirebaseAuth.ts
- lib/services/levelService.ts
- lib/types/userLevel.type.ts
- package-lock.json
- package.json
- public/features/content.md
> v3.1.2: View Played Topics in User Profile

- app/api/subscriptions/plans/route.ts
- app/pricing/layout.tsx
- components/custom/home/home-menu-button-array.tsx
- components/custom/pricing/pricing-card-carousell.tsx
- components/custom/pricing/pricing-card.tsx
- components/custom/profile/profile-subscription-card.tsx
- components/custom/profile/profile-topic-scroll-view.tsx
- components/custom/user-login-portal.tsx
- lib/services/levelService.ts
- lib/services/subscriptionService.ts
- public/html/cookie-policy.html
- public/html/privacy.html
> 249 v320 preview update policies to align with stripe

- app/api/evaluation/route.ts
- lib/admin-manager.ts
- lib/errors/google-ai-error-parser.ts
- lib/utils/authUtils.ts
Experimented with Gemini Pro for AI Evaluation. Implement better prompt to control the output format from the AI. Overall the performance of Gemini Pro evaluation is better than GPT3.5 therefore apply this change to production.
Also to save money $$
closes #261
> Update evaluation route to use Google Gemini Pro for chat completion

- .idea/.gitignore
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/jsLinters/eslint.xml
- .idea/prettier.xml
- .idea/vcs.xml
- app/about/page.tsx
- app/add-level/page.tsx
- app/ai/page.tsx
- app/globals.css
- app/layout.tsx
- app/level/[id]/page.tsx
- app/levels/layout.tsx
- app/levels/page.tsx
- app/page.tsx
- app/profile/page.tsx
- app/pwa/page.tsx
- app/result/page.tsx
- app/roadmap/page.tsx
- app/rule/layout.tsx
- app/rule/page.tsx
- app/sitemap/page.tsx
- app/whatsnew/page.tsx
- app/x/review-words/page.tsx
- components/header/index.tsx
- lib/admin-manager.ts
- lib/utils/routeUtils.ts
> Fix firefox scrollbar issue

- app/level/[id]/level-page-client-wrapper.tsx
- app/profile/server/fetch-user-completed-games.ts
- supabase/migrations/20240129194351_remote_schema.sql
also fix user can see 2 instead of 1 most recent game in profile
> Fix: logged in user cannot upload game when under FREE plan

- app/add-level/page.tsx
- app/ai/page.tsx
- app/globals.css
- app/levels/page.tsx
- app/page.tsx
- app/pricing/page.tsx
- app/result/topic-contribution-controller.tsx
- app/roadmap/roadmap.md
- components/custom/common/access-link-card.tsx
- components/custom/common/hover-perspective-container.tsx
- components/custom/home-menu-button.tsx
- components/custom/home/home-menu-button-array.tsx
- components/custom/level-card.tsx
- components/custom/pricing/pricing-card.tsx
- components/custom/profile/recent-games/profile-recent-game-card.tsx
- components/custom/profile/recent-games/profile-recent-games-scroll-view.tsx
- components/custom/profile/statistics/profile-statistics-simple-card.tsx
- components/custom/profile/topics/profile-topic-scroll-view.tsx
- components/custom/profile/topics/profile-topics-card-view.tsx
- components/custom/side-menu.tsx
- components/custom/topic-review-sheet.tsx
- components/header/user-sign-in-portal.tsx
- public/features/content.md
* Add cta appearance for AI mode. Alternate different messages and buttons when user is subscribed or not subscribed.
* Add hover perspective to pricing and profile cards
* Use hover perspective component for statistics card
> v3.1.8 ui improvements
